name: Web Build + Deployment to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Remova ou comente esta seção se não precisar instalar dependências adicionais
    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Install Flet
      run: pip install flet

    - name: Build project
      run: python webTest/src/build.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
